### ISSUE TITLE
How can I use grunt-uncss with an AngularJS application?

### ISSUE THREAD

**Issue by bernardopacheco** [addyosmani/grunt-uncss#138]
I'm just having problems to use grunt-uncss with an AngularJS application. To don't repeat myself, I've posted an answer in the SO:

http://stackoverflow.com/questions/26638782/how-can-i-use-grunt-uncss-with-an-angularjs-application?noredirect=1#comment41884839_26638782

I'll appreciate any help.

Bernardo Pacheco

**Comment by addyosmani** [comment]
I know it's been quite some time since you posted this question - was the SO answer able to help at all?

**Comment by simplesthing** [comment]
Same here, I tried using both options.urls and passing in array of urls into files, but neither seem to actually be seeing a rendered version of the app because it is cutting out all nested/specific styles of directive templates that are added at runtime. I would love to see an example of this working on a large angular app that has alot of directives.

**Comment by AndyBean** [comment]
We use Uncss on our large Angular apps and it works fine, AFTER you add all of the Angular specific and dynamic styles to the ignore sheet. Once a week, though, we forget adn someoen has to add a new style or wildcard to the ignore.

**Comment by XhmikosR** [comment]
Please ask upstream for more help.
