### ISSUE TITLE
Missing dependency of PhantomJS

### ISSUE THREAD

**Issue by bigfoot90** [addyosmani/grunt-uncss#198]
After installing `grunt-css` with command `npm install grunt-uncss --save-dev` phantomjs is missing.

```
Fatal error: spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
```

**Comment by XhmikosR** [comment]
1. this can't be an issue with grunt-uncss; we don't directly depend to phantomjs
2. CI tests are passing: https://travis-ci.org/addyosmani/grunt-uncss and https://ci.appveyor.com/project/addyosmani/grunt-uncss/branch/master
3. You are missing substantial info like your OS, node version and so on

So that being said you should take this upstream.
